package app.test;

import app.Console;
import app.model.Game;
import app.model.Guess;

dialect "mvel";
 
rule "init"
	when
		not Game()
		not Guess()
    then
        Console.out("Rule init");
end

rule "start"
	when
		game : Game();
		not Guess();
	then
		Console.out("Game");
		modify(game) { count = game.count + 1 }
		insert(new Guess(Console.getInput()));
end

rule "lesser"
	when
		game : Game(count <= maxCount)
		guess : Guess(num < game.num);
	then
		System.out.println("Guessed too low " + game.count);
		modify(game) { count = game.count + 1 }
		retract(guess)
		insert(new Guess(Console.getInput()));
end

rule "greater"
	when
		game : Game(count <= maxCount)
		guess : Guess(num > game.num);
	then
		Console.out("Guessed too high " + game.count);
		modify(game) { count = game.count + 1 }
		retract(guess)
		insert(new Guess(Console.getInput()));
end

rule "found"
	when
		game: Game(count <= maxCount)
		guess: Guess(num == game.num)
	then
		Console.out("Found");
		retract(game);
end

rule "end"
	when
		 game: Game(count > maxCount);
	then 
		Console.out("You lost");
end

